export const INCREMENT='INCREMENT';
export const DECREMENT='DECREMENT';
export const IPUT_TEXT='IPUT_TEXT';
export const COMMENT_CREATE='COMMENT_CREATE';
export const COMMENT_UPDATE='COMMENT_UPDATE';
export const COMMENT_DELETE='COMMENT_DELETE';

export const COMMENT_LOAD='COMMENT_LOAD';
export const LOADER_DISPLAY_ON='LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF='LOADER_DISPLAY_OFF';

export const ERROR_DISPLAY_ON='ERROR_DISPLAY_ON';
export const ERROR_DISPLAY_OFF='ERROR_DISPLAY_OFF';


export const POSTS_LOAD='POSTS_LOAD';
export const POSTS_DELETE='POSTS_DELETE';


